### ISSUE TITLE
Apply style guide to your Legal Page

### ISSUE THREAD

**Issue by benrobson** [PagodaNetwork/issues#10]
[![Screenshot from Gyazo](https://gyazo.com/023d09b84e49ba108000abe49a4578fa/raw)](https://gyazo.com/023d09b84e49ba108000abe49a4578fa)

https://pagodanetwork.com/legal/ [legit looks like you just copied and pasted it out of Google Docs]

**Comment by jasoryeh** [comment]
Didn't copy paste. Chose a more traditional font for legal on purpose.
