### ISSUE TITLE
Grammatical error [ , shouldn't be there]

### ISSUE THREAD

**Issue by benrobson** [PagodaNetwork/issues#11]
[![Screenshot from Gyazo](https://gyazo.com/991f89807ee7ea2033dba66071c69765/raw)](https://gyazo.com/991f89807ee7ea2033dba66071c69765)

**Comment by jasoryeh** [comment]
![image](https://user-images.githubusercontent.com/13290941/31857922-7d6dc8da-b69f-11e7-96ab-e3919d376f53.png)
