### ISSUE TITLE
The : in Staff on the staff page shouldn't be there

### ISSUE THREAD

**Issue by benrobson** [PagodaNetwork/issues#12]
[![Screenshot from Gyazo](https://gyazo.com/a56d0c5b91062d98443349130f1e5b4d/raw)](https://gyazo.com/a56d0c5b91062d98443349130f1e5b4d)

**Comment by jasoryeh** [comment]
![image](https://user-images.githubusercontent.com/13290941/31858198-a412f1a2-b6a6-11e7-96be-031e12881c8e.png)
