### ISSUE TITLE
One is red, the other is transparent issue still not resolved after my issue was closed.

### ISSUE THREAD

**Issue by benrobson** [PagodaNetwork/issues#16]
I have to make a new issue because the previous one was closed.
This has not been fixed/changed.
[![Screenshot from Gyazo](https://gyazo.com/08522827906de85c7c6e2fe02c0b7a1d/raw)](https://gyazo.com/08522827906de85c7c6e2fe02c0b7a1d)

Referring to #13

**Comment by alexanderjoe** [comment]
Ok, but it doesn't say anything about a red button, and there is no point in change the color of either of them, staff apps are just red to add emphasis.

**Comment by jasoryeh** [comment]
It is purposely transparent and red sir.

**Comment by jasoryeh** [comment]
There is no need to change it up.
