### ISSUE TITLE
'Already connecting to this server' but never actually connects

### ISSUE THREAD

**Issue by benrobson** [PagodaNetwork/issues#17]
[![Screenshot from Gyazo](https://gyazo.com/ef9cce165d5168ebb0238c50fcf84a44/raw)](https://gyazo.com/ef9cce165d5168ebb0238c50fcf84a44)

**Comment by benrobson** [comment]
I don't know if it's a bug or if you're not actually supposed to connect

**Comment by alexanderjoe** [comment]
The server could have just been down. You shouldn't really be in a UHC lobby without a game starting so whitelist is usually on.

**Comment by alexanderjoe** [comment]
I'm assuming this issue was fixed. If it wasn't open a new one, but UHC should be whitelisted/turned off if there isn't a game that day.
