### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by JapaneseSquid** [PagodaNetwork/issues#2]
Profile picture cannot be changed to another image after setting it to one

**Comment by jasoryeh** [comment]
Is this a forums problem?

**Comment by jasoryeh** [comment]
Is this your profile picture? https://pagodanetwork.com/social/images/JapaneseSquid.png

**Comment by JapaneseSquid** [comment]
Yes it is forums 
I set mine to the flag of Japan 
Then I tried changing it
Doesn't show the change to me

**Comment by alexanderjoe** [comment]
This was an issue due to how CloudFlare caches page to improve loading time, this issue should no longer exist, I will leave this open for 24 hours if there are any more issues with it.

**Comment by Palmidence** [comment]
Don't host images on your own servers, use something like Gravatar. You can get in serious legal trouble if anyone uploads illegal content and you'll be responsible

**Comment by jasoryeh** [comment]
Note Taken.

**Comment by alexanderjoe** [comment]
I will look into that.

**Comment by JapaneseSquid** [comment]
Yeah, I've tampered around a bit. Seems to be fixed.

**Comment by jasoryeh** [comment]
Closed, we've started to use miencraft characters as profile pictures, and will soon add the ability to add gravatar pics.
