### ISSUE TITLE
Suggestion: Professionalize Rules page and Staff app Q's 

### ISSUE THREAD

**Issue by JapaneseSquid** [PagodaNetwork/issues#3]
The rules are just copy pasted from the discord's rules channel, it'd be better to specify on most of them and change the wording of others

Staff App questions seemed rushed, fix wording and maybe add a few more questions/specify on the rest

**Comment by jasoryeh** [comment]
Need senior staff to finalize rules

**Comment by jasoryeh** [comment]
Also, sometimes too much professionalism ruins player's experiences.

**Comment by alexanderjoe** [comment]
Seems fixed, make a new issue if it's not.
