### ISSUE TITLE
"Find out more" text goes over the main buttons.

### ISSUE THREAD

**Issue by AbusiveUser** [PagodaNetwork/issues#4]
![e40b04726d491713ff8544a787c89d86](https://user-images.githubusercontent.com/19915020/30770494-d56a8c4e-9ff7-11e7-9b19-be243646afa2.png)

**Comment by jasoryeh** [comment]
I believe this is a screen related/browser size problem, since I only see this occur with browsers that are smaller.

**Comment by jasoryeh** [comment]
Old website, we've moved on....
