### ISSUE TITLE
I really don't think .-. should be there

### ISSUE THREAD

**Issue by benrobson** [PagodaNetwork/issues#7]
[![Screenshot from Gyazo](https://gyazo.com/23072815898396b0c17bdd36aa468371/raw)](https://gyazo.com/23072815898396b0c17bdd36aa468371)

**Comment by alexanderjoe** [comment]
Where exactly?

**Comment by benrobson** [comment]
On the home page @alexanderjoe

**Comment by benrobson** [comment]
[![Screenshot from Gyazo](https://gyazo.com/454595f75ad14364661251540a9a2c96/raw)](https://gyazo.com/454595f75ad14364661251540a9a2c96)

**Comment by alexanderjoe** [comment]
Removed.
