### ISSUE TITLE
Get rid of the ... and just capitalize the letters

### ISSUE THREAD

**Issue by benrobson** [PagodaNetwork/issues#8]
[![Screenshot from Gyazo](https://gyazo.com/72a23183b55789d12a8799dd1085bcba/raw)](https://gyazo.com/72a23183b55789d12a8799dd1085bcba)

Example:
...mods that allow you to see into others' inventories.
Mods that allow you to see into others' inventories.

**Comment by jasoryeh** [comment]
Fixed.
